### ISSUE TITLE
Console Spam

### ISSUE THREAD

**Issue by gluff95** [ollieread/TooManyGodDamnOres#1]
Every now and then on the server, the console is spammed by messages like this:

"A HarvestDropsEvent was fired with no subject block"

What does it mean and how do I make it go away?

**Comment by ollieread** [comment]
I'm going to upgrade this mod soon and add in a configuration option to silence these messages. This is because, as it states, a forge event has been fired but there is no subject block. This is often the case for things that don't actually have corresponding blocks.
