### ISSUE TITLE
Documentation is out of date

### ISSUE THREAD

**Issue by skwerlman** [ollieread/TooManyGodDamnOres#3]
In the readme, the example config looks like this:

```
# Configuration file

####################
# general
####################

general {
    S:oreCopper=IC2
    S:oreTin=IC2
}
```

However, the default config looks like this:

```
# Configuration file

exclusions {
}

replacements {
}
```

It is difficult to infer from the docs how to actually configure the mod.

**Comment by ollieread** [comment]
There's also a link in the readme:

http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1294853-1-7-2-forge-toomanygoddamnores-ore-dictionary

**Comment by skwerlman** [comment]
I did not see that; thanks
