### ISSUE TITLE
Working 1.10.2 Port

### ISSUE THREAD

**Issue by pacas00** [ollieread/TooManyGodDamnOres#6]
Recently found myself playing Minecraft again and needing this mod, So I've ported it and been using it.
Figured i might as well let you know of it's existence.

https://github.com/pacas00/TooManyGodDamnOres/tree/MC1.10.2

**Comment by ollieread** [comment]
Have you confirmed that it works? If so, I can merge this in.

**Comment by pacas00** [comment]
Yeah it works.
It also includes a config option, dumpOreDictOnLoad, to dump the ore dictionary on load. Which might help #2 .

**Comment by ollieread** [comment]
If you want to do a pull request, I can merge it in and add you as a contributor.

**Comment by ollieread** [comment]
@pacas00 is a mod like this still needed?

**Comment by pacas00** [comment]
Don't know, don't play minecraft any more.
